#!/usr/bin/env bash

CURRENT=$PWD
REPO=dpacheconr
IMAGES=$@

if [ -z "$IMAGES" ]; then
	IMAGES="loadgenerator loadgeneratorredis adservice cartservice checkoutservice currencyservice emailservice frontend loadgenerator paymentservice productcatalogservice recommendationservice shippingservice"
fi

for SERVICE in $IMAGES
do
	echo "##### Building $SERVICE #####"
	cd $CURRENT
	cd src/$SERVICE
	docker buildx build --push -t $REPO/$SERVICE -o type=image --platform=linux/arm64,linux/amd64 .
	if [ $? -ne 0 ]; then
		echo "##### Failed to build $SERVICE #####"
		exit 1
	fi
done